spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #com.amazon.redshift.jdbc42.Driver

    url: jdbc:sqlserver://cdhsqltest01.privatelink.database.chinacloudapi.cn:1433;DatabaseName=enterprisedata;encrypt=true;trustServerCertificate=true
    #jdbc:redshift://kdsa1uat-redshift-cluster.cxvowp49opna.cn-northwest-1.redshift.amazonaws.com.cn:8639/energy_test
    username: cdhuer
    #energy_user

    password: WjaG2TeZXTwYOenq
    #KZfpL0xtSfGfpKpK

    druid:
      filters: config
#      connection-properties: config.decrypt=true;config.decrypt.key=${cg_energy.db.public-key}
      connection-properties: config.decrypt=false
      initial-size: 1
      min-idle: 1
      max-active: 8
      stat-view-servlet:
        enabled: true
cg_energy:
  db:
    public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJtxskBbztz8ewXd//hZlHaJe5yG9x8z3u2I9RinBleGu4A0JGxlhNs6ArYt12xuDtj21QVcN2erpdKmK8DY/JMCAwEAAQ==
  cpm:
    point-path: https://internal-apphub.wilmar.cn/CPM2_IS/rest/ShowScreen/EnergySensors
  #    point-path: https://devhub.wilmarapps.com/CPM2_IS/rest/ShowScreen/EnergySensors
  pims:
    point-value-path: https://pimsapi.wilmar.cn/api/OSI/PIDACN/BulkLoadPointValues
#    point-value-path: https://pimsapi-dev.wilmar.cn/api/OSI/PIDACN/BulkLoadPointValues